%dev.quarkus.datasource.dev-ui.allow-sql=true
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
#quarkus.datasource.password=12345
quarkus.datasource.password=labcom2015
#quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://dbserver:5432/postgres
quarkus.http.port=9090


#quarkus.stork.authors-api.service-discovery.address-list=localhost:8080,localhost:8081
#quarkus.stork.authors-api.load-balancer.type=round-robin

#quarkus.stork.customers-api.service-discovery.type=static
#quarkus.stork.customers-api.service-discovery.address-list=localhost:7070,localhost:7071

# Configuración para Consul
# app-books usará Stork para encontrar y balancear las peticiones hacia la aplicación "app-authors" registrada en Consul.
consul.host=127.0.0.1
consul.port=8500

quarkus.stork.authors-api.service-discovery.type=consul
quarkus.stork.authors-api.service-discovery.consul-host=${consul.host}
quarkus.stork.authors-api.service-discovery.consul-port=${consul.port}
quarkus.stork.authors-api.service-discovery.application=app-authors
quarkus.stork.authors-api.service-discovery.refresh-interval=5s