api:
  insecure: true
  dashboard: true
entryPoints:
  http:
    address: ":80"
  traefik:
    address: ":8888"
providers:
  consulCatalog:
    refreshInterval: "10s"
    exposedByDefault: true
    endpoint:
      address: "127.0.0.1:8500"





